  CREATE TABLE DEHYDRATION_DB 
   (	"JOB_ID" NUMBER(6,0), 
	"SYSTEM_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CORRELATION_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"EXPIRY_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"EXCHANGE" VARCHAR2(255 BYTE), 
	"ROUTINGKEY" VARCHAR2(255 BYTE), 
	"PAYLOAD" BLOB, 
	"MIME_TYPE" VARCHAR2(255 BYTE), 
	"HEADERS" VARCHAR2(4000 BYTE), 
	"PROPERTIES" VARCHAR2(4000 BYTE), 
	 PRIMARY KEY ("JOB_ID")
   )